config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end 

  resources :bookmarks, only: [] do
    get 'import', on: :collection
    post 'bulk_insert', on: :collection
  end

  root to: 'folders#root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :folders do
    get 'childs', on: :member
    resources :bookmarks do
      put 'sync_body', on: :member
    end
  end
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  class FolderNotFound < StandardError;end
  belongs_to :folder, inverse_of: :bookmarks
  belongs_to :history, inverse_of: :bookmarks
  scope :layer_by, ->(id) { where(layer: id) }
  scope :href_like, ->(href) { where(arel_table[:href].matches("%#{href}%")) }

  #create時に件数が多い時は実行せずにアクセスされると実行するようにする
  #after_create :sync_body

  def folders=(value)
    super(value.to_json)
  end
  def folders
    JSON.parse(super)
  end
  def update_folder
    parent_id = Folder.where(folders: self.folders.to_json).first.id
    raise FolderNotFound unless parent_id
    update_attributes(folder_id: parent_id)
  end
  def nests
    folder.nests + 1
  end
  def full_path
    folder.folders.join('/') + '/' + title
  end

  def self.top_ten
    all.map{|t| URI(t.href).host rescue '' }.group_by{|t| t}.map{|t| {domain: t.first, size: t.second.count} }.sort_by{|t| t[:size]}
    #{:domain=>"www.evernote.com", :size=>409}]
    #{:domain=>"qiita.com", :size=>136},
    #{:domain=>"d.hatena.ne.jp", :size=>64},
    #{:domain=>"stackoverflow.com", :size=>47},
    #{:domain=>"dev.classmethod.jp", :size=>31},
    #{:domain=>"tabelog.com", :size=>29},
    #{:domain=>"coliss.com", :size=>24},
    #{:domain=>"github.com", :size=>22},
    #{:domain=>"liginc.co.jp", :size=>20},
    #{:domain=>"cookpad.com", :size=>15},
    #{:domain=>"www.atmarkit.co.jp", :size=>14},
    #{:domain=>"s.tabelog.com", :size=>13},
    #{:domain=>"www.infoq.com", :size=>13},
    #{:domain=>"postd.cc", :size=>13},
    #{:domain=>"morizyun.github.io", :size=>12},
    #{:domain=>"matome.naver.jp", :size=>11},
  end

  private
    def sync_body
      #urlと自身のIDを渡す
      #内部でdomainにより実行するクラスを切り替える
      CrawlerWorker.perform_async id
    end
  #private end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  def bulk_insert
    bookmark_xml_importer = BookmarkImporter::XMLImporter.new(file: bookmark_bulk_insert_params[:file])
    bookmark_xml_importer.import_async
    render json: {message: 'start import'}
  end
 
  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :href, :body)
    end
    def bookmark_bulk_insert_params
      params.require(:bookmark_bulk_insert).permit(:file)
    end
end

app/views/bookmarks/_form.html.slim
= simple_form_for(@bookmark) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :href
    = f.input :body

  .form-actions
    = f.button :submit

app/views/bookmarks/edit.html.slim
h1 Editing bookmark

== render 'form'

= link_to 'Show', @bookmark
'|
= link_to 'Back', bookmarks_path

app/views/bookmarks/index.html.slim
h1 Listing bookmarks

table
  thead
    tr
      th Title
      th Href
      th Body
      th
      th
      th

  tbody
    - @bookmarks.each do |bookmark|
      tr
        td = bookmark.title
        td = bookmark.href
        td = bookmark.body
        td = link_to 'Show', bookmark
        td = link_to 'Edit', edit_bookmark_path(bookmark)
        td = link_to 'Destroy', bookmark, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Bookmark', new_bookmark_path

app/views/bookmarks/new.html.slim
h1 New bookmark

== render 'form'

= link_to 'Back', bookmarks_path

app/views/bookmarks/show.html.slim
p#notice = notice

p
  strong Title:
  = @bookmark.title
p
  strong Href:
  = @bookmark.href
p
  strong Body:
  = @bookmark.body

= link_to 'Edit', edit_bookmark_path(@bookmark)
'|
= link_to 'Back', bookmarks_path