config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end 

  resources :bookmarks, only: [] do
    get 'import', on: :collection
    post 'bulk_insert', on: :collection
  end

  root to: 'folders#root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :folders do
    get 'childs', on: :member
    resources :bookmarks do
      put 'sync_body', on: :member
    end
  end
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  class FolderNotFound < StandardError;end
  has_many :bookmarks, inverse_of: :folder
  belongs_to :history, inverse_of: :folders
  scope :by_layer, ->(id) { where(layer: id) }
  scope :by_path, ->(path) { where(path: path) }
  scope :by_title, ->(title) { where(title: title) }
  before_validation :initialize_by_fullpath, if:  ->(t) { t.fullpath.present? }

  validates_uniqueness_of :title,  scope: :path
  validates_presence_of :title
  attr_accessor :fullpath

  def to_s
    path.join('/')
  end
  def title_with_path
    path.to_s + '/' + title.to_s
  end
  def parent_folders
    if is_root?
      []
    else
      folders = path.split('/')
      folders.pop
      folders
    end
  end

  def parent_folder
    unless is_root?
      Folder.find(parent_id)
    end
  end


  def is_root?
    self.path.nil? || self.path.split('/').count == 0
  end
  def has_parent?
    parent_id
  end
  def initialize_by_fullpath
    self.title, self.layer, self.path = Folder.divide_fullpath(self.fullpath.dup).values
  end
  def child_ids
    childs.pluck(:id)
  end
  def childs
    Folder.where(parent_id: id)
  end



  def update_parents 
    unless is_root?
      from_root_folder = []
      path.split('/').each do |folder|
        parent_id = Folder.find_by_fullpath(from_root_folder.dup).try(:id)
        #Folder.find_or_create_by(path: from_root_folder.join('/'), title: folder, history_id: history_id)
        from_root_folder << folder
        Folder.find_or_create_by_fullpath(from_root_folder.dup, history_id: history_id, parent_id: parent_id)
      end
      #path_array = path.split('/')
      #title = path_array.pop
      #path = path_array.join('/')

      # 自身の親を探す
      parent_id = Folder.find_by_fullpath(path).try(:id)
      update_attributes(parent_id: parent_id) if parent_id
    end
  end

  def self.find_or_create_by_fullpath(from_root_folder, option)
    puts from_root_folder
    unless folder = Folder.find_by_fullpath(from_root_folder.dup)
      hash = Folder.divide_fullpath(from_root_folder.dup)
      folder = Folder.create(hash.merge(option))
    end
    folder
  end
  def self.find_by_fullpath(from_root_path)
    title, layer, path = Folder.divide_fullpath(from_root_path).values
    #puts from_root_path
    #puts [title,layer,path]
    Folder.by_path(path).by_title(title).by_layer(layer).first
  end
  def self.divide_fullpath(from_root_path)
    ret_hash = {}
    if from_root_path.is_a?(String)
      from_root_path = from_root_path.split('/').reject(&:blank?)
    end
    ret_hash[:title] = from_root_path.pop
    ret_hash[:layer] = from_root_path.size + 1
    ret_hash[:path] = from_root_path.join('/')
    #puts ret_hash
    ret_hash
  end

  #  Folder.all.order(layer: :desc).in_batches(of: 3) do |temp|
  #  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]


  def root
    @history = History.new
    @folders = Folder.by_layer(1).order(:id).page(params[:page])
    @layer = 0
  end



  # GET /folders
  # GET /folders.json
  def index
    #@history = History.find(params[:history_id])
    @folders = @history.folders.by_layer(1).order(:id).page(params[:page])
    @layer = 0
  end

  def childs
    @folder = Folder.find(params[:id])
    @folders = Folder.where(parent_id: params[:id])
    @layer = @folder.layer
    render layout: nil
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
    @history = History.find(params[:history_id])
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:history_id, :layler, :path, :title)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_bookmark.html.slim
section.section--center.mdl-grid.mdl-grid--no-spacing.mdl-shadow--2dp
  .mdl-card.mdl-cell.mdl-cell--12-col
    .mdl-card__supporting-text
      h4
        = bookmark.title
      = truncate bookmark.body, length: 50
    .mdl-card__actions
      a.mdl-button[href="#"]
        | Read our features
  button#btn3.mdl-button.mdl-js-button.mdl-js-ripple-effect.mdl-button--icon[data-upgraded=",MaterialButton,MaterialRipple"]
    i.material-icons
      | more_vert
    span.mdl-button__ripple-container
      span.mdl-ripple
  .mdl-menu__container.is-upgraded
    .mdl-menu__outline.mdl-menu--bottom-right
    ul.mdl-menu.mdl-js-menu.mdl-menu--bottom-right[for="btn3" data-upgraded=",MaterialMenu"]
      li.mdl-menu__item[tabindex="-1"]
        | Lorem
      li.mdl-menu__item[disabled="" tabindex="-1"]
        | Ipsum
      li.mdl-menu__item[tabindex="-1"]
        | Dolor

app/views/folders/_bookmarks.html.slim
section.section--center.mdl-grid.mdl-grid--no-spacing.mdl-shadow--2dp
  .mdl-card.mdl-cell.mdl-cell--12-col
    .mdl-card__supporting-text
      h4
        = bookmark.title
      = truncate bookmark.body, length: 50
    .mdl-card__actions
      a.mdl-button[href="#"]
        | Read our features
  button#btn3.mdl-button.mdl-js-button.mdl-js-ripple-effect.mdl-button--icon[data-upgraded=",MaterialButton,MaterialRipple"]
    i.material-icons
      | more_vert
    span.mdl-button__ripple-container
      span.mdl-ripple
  .mdl-menu__container.is-upgraded
    .mdl-menu__outline.mdl-menu--bottom-right
    ul.mdl-menu.mdl-js-menu.mdl-menu--bottom-right[for="btn3" data-upgraded=",MaterialMenu"]
      li.mdl-menu__item[tabindex="-1"]
        | Lorem
      li.mdl-menu__item[disabled="" tabindex="-1"]
        | Ipsum
      li.mdl-menu__item[tabindex="-1"]
        | Dolor

app/views/folders/_form.html.slim
= form_for @folder do |f|
  - if @folder.errors.any?
    #error_explanation
      h2 = "#{pluralize(@folder.errors.count, "error")} prohibited this folder from being saved:"
      ul
        - @folder.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :history_id
    = f.number_field :history_id
  .field
    = f.label :layer
    = f.number_field :layer
  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit

app/views/folders/_list.html.slim
.layer[data-layer="#{@layer}"]
  .horizontal-scroll-bar-container
    .horizontal-scroll-bar-modules[data-layer="#{@layer}"]
      - if @folders.present?
        - @folders.each do |folder|
          .horizontal-scroll-bar-module[data-href="#{childs_folder_path(folder)}"] 
            = folder.title
      - else
        | no data
  - if @folder
    .bookmarks
      - @folder.bookmarks.each do |bookmark|
        .outer
          = render 'bookmark', bookmark: bookmark
          /span.mdl-chip.bookmark
            span.mdl-chip__text
              = bookmark.title.truncate(10)

app/views/folders/child_folders.html.slim
= render 'list'

app/views/folders/childs.html.slim
= render 'list'

app/views/folders/edit.html.slim
h1 Editing folder

== render 'form'

= link_to 'Show', @folder
'|
= link_to 'Back', folders_path

app/views/folders/index.html.slim
#results
  /ここのケツにコンテンツを追加していく
  = render 'list'
br

= link_to 'New Folder', new_history_folder_path(@history)

app/views/folders/new.html.slim
h1 New folder

== render 'form'

= link_to 'Back', folders_path

app/views/folders/root.html.slim
#results
  /ここのケツにコンテンツを追加していく
  = render 'list'
br
div#bookmark-import[class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--accent mdl-color-text--accent-contrast"]
  | Bookmarkをインポート

app/views/folders/show.html.slim
p#notice = notice

p
  strong History:
  = @folder.history_id
p
  strong Layler:
  = @folder.layer
p
  strong Path:
  = @folder.path
p
  strong Title:
  = @folder.title