config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end 

  resources :bookmarks, only: [] do
    get 'import', on: :collection
    post 'bulk_insert', on: :collection
  end

  root to: 'folders#root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :folders do
    get 'childs', on: :member
    resources :bookmarks do
      put 'sync_body', on: :member
    end
  end
end

app/views/layouts/_breadcrumbs.html.slim
.title
  | Responsive Breadcrumbs
.breadcrumbs
  .inner
    ul.cf
      li
        a
          span 1
          span Home
      li
        a.active
          span 2
          span Service
      li
        a
          span 3
          span Menu
      li
        a
          span 4
          span Checkout
      li
        a
          span 5
          span Success

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | BookmarkReader5
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .demo-layout-waterfall.mdl-layout.mdl-js-layout
      header.mdl-layout__header.mdl-layout__header--waterfall
        .mdl-layout__header-row
          span.mdl-layout-title
            | BookmarkReader
          .mdl-layout-spacer
          .mdl-textfield.mdl-js-textfield.mdl-textfield--expandable.mdl-textfield--floating-label.mdl-textfield--align-right
            label.mdl-button.mdl-js-button.mdl-button--icon[for="waterfall-exp"]
              i.material-icons
                | search
            .mdl-textfield__expandable-holder
              input#waterfall-exp.mdl-textfield__input[type="text" name="sample"]
        .mdl-layout__header-row
          .mdl-layout-spacer
          nav.mdl-navigation
            a.mdl-navigation__link[href=""]
              | Link
            a.mdl-navigation__link[href=""]
              | Link
            a.mdl-navigation__link[href=""]
              | Link
            a.mdl-navigation__link[href=""]
              | Link
      .mdl-layout__drawer
        span.mdl-layout-title
          | BookmarkReader
        nav.mdl-navigation
          a.mdl-navigation__link[href=""]
            | Link
          a.mdl-navigation__link[href=""]
            | Link
          a.mdl-navigation__link[href=""]
            | Link
          a.mdl-navigation__link[href=""]
            | Link
      main.mdl-layout__content
        .page-content
          = yield
  #bulk_insert_bookmarks_modal.modal.fade[role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"]
   .modal-dialog[role="document"]
     .modal-content
       = form_tag bulk_insert_bookmarks_path, multipart: true, remote: true, id: 'bookmark-import-form' do
         = hidden_field_tag :authenticity_token, form_authenticity_token
         .modal-header
           button.close[type="button" data-dismiss="modal" aria-hidden="true" aria-labelledby="myModalLabel"]
             | ×
           h4.modal-title
             | エクスポートしたファイルを選択してください
         .modal-body
           = file_field_tag 'bookmark_bulk_insert[file]'
         .modal-footer
           button.btn.btn-default[type="button" data-dismiss="modal"]
             | Close
           button.btn.btn-primary[type="button"]
             = submit_tag '送信'